include:
  - project: zg-container-platform/gitlab-templates/k8s-service-cd-templates
    file:
      - pipeline.yml
      - deployments/zillow.yml
    ref: v1
  - project: devex/archetypes/nodejs-archetype
    file: pipeline.yml
    ref: v1
  - project: core-tech/orca/zg-graph/public-pipelines/zg-graph-schema-registration
    file: zgcp.yml

variables:
  DEPLOY_DEV: "true"
  DEPLOY_STAGE: "false"
  DEPLOY_PROD: "false"
  DATADOG_ENABLED: "false"
  DATADOG_APM_ENABLED: "true"
  PANOPTES_ENABLED: "true"
  SNYK_MONITOR: "docker,node"
  DOCKER_BUILD_OPTIONS: "--build-arg ZG_NPM_TOKEN=${ZG_NPM_TOKEN}"

  # Schema registration variables
  SUBGRAPH_SCHEMA_FILE: "src/graphql/__generated__/schema.graphql"
  ENABLE_PROD_SCHEMA_RELEASE: "false"
  CONTACT_DESCRIPTION: "Node.js subgraph archetype using Apollo Server."
  INCLUDE_ABINCLUDE: "false"
